// Generated by XCloud DevOps for Codegen, refer: http://dts.devops.wl4g.com

/*
 * Copyright 2017 ~ 2025 the original author or authors. <wanglsir@gmail.com, 983708408@qq.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.wl4g.devops.doc.service.impl;

import com.github.pagehelper.PageHelper;
import com.wl4g.components.core.bean.BaseBean;
import com.wl4g.components.core.bean.model.PageModel;
import com.wl4g.devops.common.bean.doc.EnterpriseGroup;
import com.wl4g.devops.common.bean.doc.EnterpriseProject;
import com.wl4g.devops.doc.data.EnterpriseGroupDao;
import com.wl4g.devops.doc.data.EnterpriseProjectDao;
import com.wl4g.devops.doc.service.EnterpriseGroupService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

import static com.wl4g.components.common.lang.Assert2.notNullOf;
import static java.util.Objects.isNull;

/**
 *  service implements of {@link EnterpriseGroup}
 *
 * @author root
 * @version master
 * @Date 
 * @since v1.0
 */
@Service
public class EnterpriseGroupServiceImpl implements EnterpriseGroupService {

    @Autowired
    private EnterpriseGroupDao enterpriseGroupDao;

    @Autowired
    private EnterpriseProjectDao enterpriseProjectDao;

    @Override
    public PageModel<EnterpriseGroup> page(PageModel<EnterpriseGroup> pm, EnterpriseGroup enterpriseGroup) {
        pm.page(PageHelper.startPage(pm.getPageNum(), pm.getPageSize(), true));
        List<EnterpriseGroup> list = enterpriseGroupDao.list(enterpriseGroup);
        for(EnterpriseGroup li : list){
            List<EnterpriseProject> enterpriseProjects = enterpriseProjectDao.selectByGroupId(li.getId());
            li.setEnterpriseProjectList(enterpriseProjects);
        }
        pm.setRecords(list);
        return pm;
    }

    @Override
    public int save(EnterpriseGroup enterpriseGroup) {
        if (isNull(enterpriseGroup.getId())) {
        	enterpriseGroup.preInsert();
            return enterpriseGroupDao.insertSelective(enterpriseGroup);
        } else {
        	enterpriseGroup.preUpdate();
            return enterpriseGroupDao.updateByPrimaryKeySelective(enterpriseGroup);
        }
    }

    @Override
    public EnterpriseGroup detail(Long id) {
        notNullOf(id, "id");
        return enterpriseGroupDao.selectByPrimaryKey(id);
    }

    @Override
    public int del(Long id) {
        notNullOf(id, "id");
        EnterpriseGroup enterpriseGroup = new EnterpriseGroup();
        enterpriseGroup.setId(id);
        enterpriseGroup.setDelFlag(BaseBean.DEL_FLAG_DELETE);
        return enterpriseGroupDao.updateByPrimaryKeySelective(enterpriseGroup);
    }

}
