// Generated by XCloud DevOps for Codegen, refer: http://dts.devops.wl4g.com

/*
 * Copyright 2017 ~ 2025 the original author or authors. <wanglsir@gmail.com, 983708408@qq.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.wl4g.devops.doc.service.impl;

import static com.wl4g.components.common.lang.Assert2.notNullOf;
import com.wl4g.components.core.bean.model.PageModel;
import com.github.pagehelper.PageHelper;
import com.wl4g.components.core.bean.BaseBean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.wl4g.devops.common.bean.doc.EnterpriseRepositoryGroup;
import com.wl4g.devops.doc.data.EnterpriseRepositoryGroupDao;
import com.wl4g.devops.doc.service.EnterpriseRepositoryGroupService;

import static java.util.Objects.isNull;

/**
 *  service implements of {@link EnterpriseRepositoryGroup}
 *
 * @author root
 * @version 0.0.1-SNAPSHOT
 * @Date 
 * @since v1.0
 */
@Service
public class EnterpriseRepositoryGroupServiceImpl implements EnterpriseRepositoryGroupService {

    @Autowired
    private EnterpriseRepositoryGroupDao enterpriseRepositoryGroupDao;

    @Override
    public PageModel<EnterpriseRepositoryGroup> page(PageModel<EnterpriseRepositoryGroup> pm, EnterpriseRepositoryGroup enterpriseRepositoryGroup) {
        pm.page(PageHelper.startPage(pm.getPageNum(), pm.getPageSize(), true));
        pm.setRecords(enterpriseRepositoryGroupDao.list(enterpriseRepositoryGroup));
        return pm;
    }

    @Override
    public int save(EnterpriseRepositoryGroup enterpriseRepositoryGroup) {
        if (isNull(enterpriseRepositoryGroup.getId())) {
        	enterpriseRepositoryGroup.preInsert();
            return enterpriseRepositoryGroupDao.insertSelective(enterpriseRepositoryGroup);
        } else {
        	enterpriseRepositoryGroup.preUpdate();
            return enterpriseRepositoryGroupDao.updateByPrimaryKeySelective(enterpriseRepositoryGroup);
        }
    }

    @Override
    public EnterpriseRepositoryGroup detail(Long id) {
        notNullOf(id, "id");
        return enterpriseRepositoryGroupDao.selectByPrimaryKey(id);
    }

    @Override
    public int del(Long id) {
        notNullOf(id, "id");
        EnterpriseRepositoryGroup enterpriseRepositoryGroup = new EnterpriseRepositoryGroup();
        enterpriseRepositoryGroup.setId(id);
        enterpriseRepositoryGroup.setDelFlag(BaseBean.DEL_FLAG_DELETE);
        return enterpriseRepositoryGroupDao.updateByPrimaryKeySelective(enterpriseRepositoryGroup);
    }

}
