// Generated by XCloud DevOps for Codegen, refer: http://dts.devops.wl4g.com

/*
 * Copyright 2017 ~ 2025 the original author or authors. <wanglsir@gmail.com, 983708408@qq.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.wl4g.devops.doc.service.impl;

import com.github.pagehelper.PageHelper;
import com.wl4g.components.core.bean.BaseBean;
import com.wl4g.components.core.bean.model.PageModel;
import com.wl4g.devops.common.bean.doc.EnterpriseOas3Api;
import com.wl4g.devops.doc.data.EnterpriseOas3ApiDao;
import com.wl4g.devops.doc.service.EnterpriseOas3ApiService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import static com.wl4g.components.common.lang.Assert2.notNullOf;
import static java.util.Objects.isNull;

/**
 *  service implements of {@link EnterpriseOas3Api}
 *
 * @author root
 * @version 0.0.1-SNAPSHOT
 * @Date 
 * @since v1.0
 */
@Service
public class EnterpriseOas3ApiServiceImpl implements EnterpriseOas3ApiService {

    @Autowired
    private EnterpriseOas3ApiDao enterpriseOas3ApiDao;

    @Override
    public PageModel<EnterpriseOas3Api> page(PageModel<EnterpriseOas3Api> pm, EnterpriseOas3Api enterpriseOas3Api) {
        pm.page(PageHelper.startPage(pm.getPageNum(), pm.getPageSize(), true));
        pm.setRecords(enterpriseOas3ApiDao.list(enterpriseOas3Api));
        return pm;
    }

    @Override
    public int save(EnterpriseOas3Api enterpriseOas3Api) {
        if (isNull(enterpriseOas3Api.getId())) {
        	enterpriseOas3Api.preInsert();
            return enterpriseOas3ApiDao.insertSelective(enterpriseOas3Api);
        } else {
        	enterpriseOas3Api.preUpdate();
            return enterpriseOas3ApiDao.updateByPrimaryKeySelective(enterpriseOas3Api);
        }
    }

    @Override
    public EnterpriseOas3Api detail(Long id) {
        notNullOf(id, "id");
        return enterpriseOas3ApiDao.selectByPrimaryKey(id);
    }

    @Override
    public int del(Long id) {
        notNullOf(id, "id");
        EnterpriseOas3Api enterpriseOas3Api = new EnterpriseOas3Api();
        enterpriseOas3Api.setId(id);
        enterpriseOas3Api.setDelFlag(BaseBean.DEL_FLAG_DELETE);
        return enterpriseOas3ApiDao.updateByPrimaryKeySelective(enterpriseOas3Api);
    }

}
