// Generated by XCloud DevOps for Codegen, refer: http://dts.devops.wl4g.com

/*
 * Copyright 2017 ~ 2025 the original author or authors. <wanglsir@gmail.com, 983708408@qq.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.wl4g.devops.doc.service.impl;

import com.github.pagehelper.PageHelper;
import com.wl4g.components.core.bean.BaseBean;
import com.wl4g.components.core.bean.model.PageModel;
import com.wl4g.devops.common.bean.doc.EnterpriseOas3Components;
import com.wl4g.devops.doc.data.EnterpriseOas3ComponentsDao;
import com.wl4g.devops.doc.service.EnterpriseOas3ComponentsService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import static com.wl4g.components.common.lang.Assert2.notNullOf;
import static java.util.Objects.isNull;

/**
 *  service implements of {@link EnterpriseOas3Components}
 *
 * @author root
 * @version 0.0.1-SNAPSHOT
 * @Date 
 * @since v1.0
 */
@Service
public class EnterpriseOas3ComponentsServiceImpl implements EnterpriseOas3ComponentsService {

    @Autowired
    private EnterpriseOas3ComponentsDao enterpriseOas3ComponentsDao;

    @Override
    public PageModel<EnterpriseOas3Components> page(PageModel<EnterpriseOas3Components> pm, EnterpriseOas3Components enterpriseOas3Components) {
        pm.page(PageHelper.startPage(pm.getPageNum(), pm.getPageSize(), true));
        pm.setRecords(enterpriseOas3ComponentsDao.list(enterpriseOas3Components));
        return pm;
    }

    @Override
    public int save(EnterpriseOas3Components enterpriseOas3Components) {
        if (isNull(enterpriseOas3Components.getId())) {
        	enterpriseOas3Components.preInsert();
            return enterpriseOas3ComponentsDao.insertSelective(enterpriseOas3Components);
        } else {
        	enterpriseOas3Components.preUpdate();
            return enterpriseOas3ComponentsDao.updateByPrimaryKeySelective(enterpriseOas3Components);
        }
    }

    @Override
    public EnterpriseOas3Components detail(Long id) {
        notNullOf(id, "id");
        return enterpriseOas3ComponentsDao.selectByPrimaryKey(id);
    }

    @Override
    public int del(Long id) {
        notNullOf(id, "id");
        EnterpriseOas3Components enterpriseOas3Components = new EnterpriseOas3Components();
        enterpriseOas3Components.setId(id);
        enterpriseOas3Components.setDelFlag(BaseBean.DEL_FLAG_DELETE);
        return enterpriseOas3ComponentsDao.updateByPrimaryKeySelective(enterpriseOas3Components);
    }

}
