// Generated by XCloud DevOps for Codegen, refer: http://dts.devops.wl4g.com

/*
 * Copyright 2017 ~ 2025 the original author or authors. <wanglsir@gmail.com, 983708408@qq.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.wl4g.devops.doc.service.impl;

import com.github.pagehelper.PageHelper;
import com.wl4g.components.core.bean.BaseBean;
import com.wl4g.components.core.bean.model.PageModel;
import com.wl4g.devops.common.bean.doc.EnterpriseOas3Tags;
import com.wl4g.devops.doc.data.EnterpriseOas3TagsDao;
import com.wl4g.devops.doc.service.EnterpriseOas3TagsService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import static com.wl4g.components.common.lang.Assert2.notNullOf;
import static java.util.Objects.isNull;

/**
 *  service implements of {@link EnterpriseOas3Tags}
 *
 * @author root
 * @version 0.0.1-SNAPSHOT
 * @Date 
 * @since v1.0
 */
@Service
public class EnterpriseOas3TagsServiceImpl implements EnterpriseOas3TagsService {

    @Autowired
    private EnterpriseOas3TagsDao enterpriseOas3TagsDao;

    @Override
    public PageModel<EnterpriseOas3Tags> page(PageModel<EnterpriseOas3Tags> pm, EnterpriseOas3Tags enterpriseOas3Tags) {
        pm.page(PageHelper.startPage(pm.getPageNum(), pm.getPageSize(), true));
        pm.setRecords(enterpriseOas3TagsDao.list(enterpriseOas3Tags));
        return pm;
    }

    @Override
    public int save(EnterpriseOas3Tags enterpriseOas3Tags) {
        if (isNull(enterpriseOas3Tags.getId())) {
        	enterpriseOas3Tags.preInsert();
            return enterpriseOas3TagsDao.insertSelective(enterpriseOas3Tags);
        } else {
        	enterpriseOas3Tags.preUpdate();
            return enterpriseOas3TagsDao.updateByPrimaryKeySelective(enterpriseOas3Tags);
        }
    }

    @Override
    public EnterpriseOas3Tags detail(Long id) {
        notNullOf(id, "id");
        return enterpriseOas3TagsDao.selectByPrimaryKey(id);
    }

    @Override
    public int del(Long id) {
        notNullOf(id, "id");
        EnterpriseOas3Tags enterpriseOas3Tags = new EnterpriseOas3Tags();
        enterpriseOas3Tags.setId(id);
        enterpriseOas3Tags.setDelFlag(BaseBean.DEL_FLAG_DELETE);
        return enterpriseOas3TagsDao.updateByPrimaryKeySelective(enterpriseOas3Tags);
    }

}
