// Generated by XCloud DevOps for Codegen, refer: http://dts.devops.wl4g.com

/*
 * Copyright 2017 ~ 2025 the original author or authors. <wanglsir@gmail.com, 983708408@qq.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.wl4g.devops.common.bean.doc;

import com.wl4g.components.core.bean.BaseBean;
import javax.validation.constraints.NotNull;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

/**
 * {@link EnterpriseOas3Api}
 *
 * @author root
 * @version 0.0.1-SNAPSHOT
 * @Date Dec 10, 2020
 * @since v1.0
 */
@Getter
@Setter
@AllArgsConstructor(access = AccessLevel.PUBLIC)
public class EnterpriseOas3Api extends BaseBean {
    private static final long serialVersionUID = 637823995976806912L;

    /**
     * 
     */
    @NotNull
    private String name;

    /**
     * 跟project_version_id
     */
    @NotNull
    private Long versionId;

    /**
     * API族(类型)，1：tcp/udp(长连接)binary协议，2：基于http协议
     */
    @NotNull
    private String apiFamily;

    /**
     * 接口端点地址信息，json格式，示例：  api_family=1时，如（查询设备功率）： {'action':'QUERY_POWER','properties':{}} ---------- api_family=2时，如（查询用户信息）： {'method':'POST','path':'/iam/user/query','properties':{}}
     */
    @NotNull
    private String endpointJson;

    /**
     * 请求响应消息结构定义
     */
    @NotNull
    private String messageStruct;

    /**
     * 接口标签Ids逗号分隔
     */
    private String tagIds;

    /**
     * 
     */
    private String remark;

    /**
     * 组织编码
     */
    private String organizationCode;

    public EnterpriseOas3Api() {
    }

    public EnterpriseOas3Api withName(String name) {
        setName(name);
        return this;
    }

    public EnterpriseOas3Api withVersionId(Long versionId) {
        setVersionId(versionId);
        return this;
    }

    public EnterpriseOas3Api withApiFamily(String apiFamily) {
        setApiFamily(apiFamily);
        return this;
    }

    public EnterpriseOas3Api withEndpointJson(String endpointJson) {
        setEndpointJson(endpointJson);
        return this;
    }

    public EnterpriseOas3Api withMessageStruct(String messageStruct) {
        setMessageStruct(messageStruct);
        return this;
    }

    public EnterpriseOas3Api withTagIds(String tagIds) {
        setTagIds(tagIds);
        return this;
    }

    public EnterpriseOas3Api withRemark(String remark) {
        setRemark(remark);
        return this;
    }

    public EnterpriseOas3Api withOrganizationCode(String organizationCode) {
        setOrganizationCode(organizationCode);
        return this;
    }
}