// Generated by XCloud DevOps for Codegen, refer: http://dts.devops.wl4g.com

/*
 * Copyright 2017 ~ 2025 the original author or authors. <wanglsir@gmail.com, 983708408@qq.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.wl4g.devops.doc.service;

import com.wl4g.components.core.bean.model.PageModel;
import com.wl4g.devops.common.bean.doc.EnterpriseDocument;

/**
 *  service of {@link EnterpriseDocument}
 *
 * @author root
 * @version master
 * @Date 
 * @since v1.0
 */
public interface EnterpriseDocumentService {

    /**
     *  page query.
     *
     * @param pm
     * @param enterpriseDocument
     * @return 
     */
    PageModel<EnterpriseDocument> page(PageModel<EnterpriseDocument> pm, EnterpriseDocument enterpriseDocument);

    /**
     *  save.
     *
     * @param enterpriseDocument
     * @return 
     */
    int save(EnterpriseDocument enterpriseDocument);

    /**
     *  detail query.
     *
     * @param id
     * @return 
     */
    EnterpriseDocument detail(Long id);

    /**
     *  delete.
     *
     * @param id
     * @return 
     */
    int del(Long id);

}

