# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Environment(SpringBoot Feign for Pro) configuration. ####
#

spring:
  xcloud:
    component:
      rpc:
        feign:
          #default-url: http://n1.devops.wl4gsafecloudcs.com:18081/doc-facade
          default-url: http://n1.devops.wl4gsafecloudcs.com:${provider.serverPort}${provider.contextPath}
          default-log-level: BASIC # NONE|BASIC|HEADERS|FULL
          client-provider: okhttp3 # http2Client|okhttp3, default to okhttp3
          max-idle-connections: 520
          connect-timeout: 11000
          read-timeout: 12000
