# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Configuration of specical on which DoPaaS(umc-manager) service(uat). ####
#
spring:
  infra:
    support:
        notification:
          mail:
            host: smtp.sina.com
            port: 465
            username: safec7782@sina.com
            password: safec7782
            protocol: smtp
          sms:
            aliyun:
              accessKeyId: ${ALIYUN_KEY}
              accessKeySecret: ${ALIYUN_SECRET}
          vms:
            aliyun:
              accessKeyId: ${ALIYUN_KEY}
              accessKeySecret: ${ALIYUN_SECRET}
              calledShowNumber: 055162153866
    iam:
      cors:
        rules:
          '[/**]':
            allows-origins:
              - https://${DOPAAS_ZONE:wl4g.uat}
              - http://${DOPAAS_ZONE:wl4g.uat}
              - https://*.${DOPAAS_ZONE:wl4g.uat}
              - http://*.${DOPAAS_ZONE:wl4g.uat}
      acl:
        secure: false # Turn off protection will trust any same intranet IP.
        allowIpRange: ${DOPAAS_IAM_ACL_ALLOW:127.0.0.1}
        denyIpRange: ${DOPAAS_IAM_ACL_DENY}
      client:
        server-uri: http://iam.${DOPAAS_ZONE:wl4g.uat}/iam-web
        unauthorized-uri: ${spring.xcloud.iam.client.server-uri}/view/403.html
        success-uri: http://dopaas.${DOPAAS_ZONE:wl4g.uat}/#/umc/config

# Spring-security config.
security.user:
  name: sba_user
  password: hnGsFm6k0klJP9j

opentsdb:
  url: http://10.0.0.57
  port: 4242