// Generated by XCloud DevOps for Codegen, refer: http://dts.devops.wl4g.com

/*
 * Copyright 2017 ~ 2025 the original author or authors. <wanglsir@gmail.com, 983708408@qq.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.wl4g.devops.doc.data;

import com.wl4g.devops.common.bean.doc.EnterpriseOas3Components;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * {@link EnterpriseOas3Components}
 *
 * @author root
 * @version 0.0.1-SNAPSHOT
 * @Date Dec 10, 2020
 * @since v1.0
 */
public interface EnterpriseOas3ComponentsDao {

    int insertSelective(EnterpriseOas3Components enterpriseOas3Components);

    int deleteByPrimaryKey(Long id);

    EnterpriseOas3Components selectByPrimaryKey(Long id);

    List<EnterpriseOas3Components> selectByVersionId(Long versionId);

    int updateByPrimaryKeySelective(EnterpriseOas3Components enterpriseOas3Components);

    int updateByPrimaryKey(EnterpriseOas3Components enterpriseOas3Components);

    List<EnterpriseOas3Components> list(@Param("enterpriseOas3Components") EnterpriseOas3Components enterpriseOas3Components);

}