version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.5

    working_directory: /go/src/github.com/magiconair/properties
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
