#### COSS(Composite Object Storage Service) A composite object storage service based on spring cloud. It does not store data on its own, Supports bridging to other storage media, such as Hdfs, Aliyun OSS, Aws S3, GlusterFS, etc

##### Usage scenario description:
- 1. If you are only used for demo and demonstration, you only need to use the default local (or NFS share) file system, that is, you do not need to deploy any coss-xx extension module.


- 2. The coss-hdfs extension module can be used if your use scenarios tend to archive more storage, write more read less common scenarios.


- 3. coss-glusterfs extension module. If your scenario depends on POSIX series standard file interface, for example: use spark ml for distributed machine learning, When the sample file is large, the sample file can be generated by an external program, written to glusterfs by the cost API, and then read directly from the glusterfs directory of the mount in the spark program.


- 4. coss-aliyunoss, coss-awss3 and other extension modules are only used to bridge oss of cloud manufacturers. For specific use scenarios, please refer to the corresponding cloud manufacturer's documentation. The advantages of integration are as follows: Enterprise provides unified object/file storage management based on devops, For example, at the later stage of a start-up project, it needs 
to be migrated to a new cloud for cost reasons service provider, the upper code does not need to be changed.