# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Configuration of middleware on which DoPaaS(urm-facade) service(uat) depends. ####
#
spring:
  xcloud:
    component:
      support:
        # Redis configuration.
        jedis:
          passwd: ${URM_DOPAAS_REDIS_PASSWD:123456}
          connect-timeout: 10000
          max-attempts: 10
          # Redis server nodes, support standalone mode single node and cluster mode multiple nodes, separated by commas.
          nodes: ${URM_DOPAAS_REDIS_NODES:redis.wl4g.uat:6379,redis.wl4g.uat:6380,redis.wl4g.uat:6381,redis.wl4g.uat:7379,redis.wl4g.uat:7380,redis.wl4g.uat:7381}
  # Datasource configuration.
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: ${URM_DOPAAS_DB_URL:jdbc:mysql://rds.wl4g.uat:3306/dopaas_uds?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&autoReconnect=true}
      username: ${URM_DOPAAS_DB_USER:dopaas_urm}
      password: ${URM_DOPAAS_DB_PASSWD:123456}
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall
      log-slow-sql: true