// Generated by XCloud DoPaaS for Codegen, refer: http://dts.devops.wl4g.com

/*
 * Copyright 2017 ~ 2025 the original author or authors. <wanglsir@gmail.com, 983708408@qq.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.wl4g.dopaas.udm.service.impl;

import static com.wl4g.component.common.lang.Assert2.notNullOf;
import static java.util.Objects.isNull;

import java.util.List;

import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.wl4g.component.core.bean.BaseBean;
import com.wl4g.component.core.page.PageHolder;
import com.wl4g.dopaas.common.bean.udm.EnterpriseRepositoryGroup;
import com.wl4g.dopaas.udm.data.EnterpriseRepositoryDao;
import com.wl4g.dopaas.udm.data.EnterpriseRepositoryGroupDao;
import com.wl4g.dopaas.udm.service.EnterpriseRepositoryGroupService;
import com.wl4g.dopaas.udm.service.model.EnterpriseRepositoryGroupPageRequest;

/**
 * service implements of {@link EnterpriseRepositoryGroup}
 *
 * @author root
 * @version 0.0.1-SNAPSHOT
 * @Date
 * @since v1.0
 */
@Service
public class EnterpriseRepositoryGroupServiceImpl implements EnterpriseRepositoryGroupService {

	private @Autowired EnterpriseRepositoryGroupDao enterpriseRepositoryGroupDao;

	private @Autowired EnterpriseRepositoryDao enterpriseRepositoryDao;

	@Override
	public PageHolder<EnterpriseRepositoryGroup> page(EnterpriseRepositoryGroupPageRequest enterpriseRepositoryGroupPageRequest) {
		PageHolder<EnterpriseRepositoryGroup> pm = enterpriseRepositoryGroupPageRequest.getPm();
		pm.useCount().bind();
		EnterpriseRepositoryGroup enterpriseRepositoryGroup = new EnterpriseRepositoryGroup();
		BeanUtils.copyProperties(enterpriseRepositoryGroupPageRequest, enterpriseRepositoryGroup);
		List<EnterpriseRepositoryGroup> list = enterpriseRepositoryGroupDao.list(enterpriseRepositoryGroup);
		for (EnterpriseRepositoryGroup group : list) {
			group.setEnterpriseRepositories(enterpriseRepositoryDao.selectByGroupId(group.getId()));
		}
		pm.setRecords(list);
		return pm;
	}

	@Override
	public int save(EnterpriseRepositoryGroup enterpriseRepositoryGroup) {
		if (isNull(enterpriseRepositoryGroup.getId())) {
			enterpriseRepositoryGroup.preInsert();
			return enterpriseRepositoryGroupDao.insertSelective(enterpriseRepositoryGroup);
		} else {
			enterpriseRepositoryGroup.preUpdate();
			return enterpriseRepositoryGroupDao.updateByPrimaryKeySelective(enterpriseRepositoryGroup);
		}
	}

	@Override
	public EnterpriseRepositoryGroup detail(Long id) {
		notNullOf(id, "id");
		return enterpriseRepositoryGroupDao.selectByPrimaryKey(id);
	}

	@Override
	public int del(Long id) {
		notNullOf(id, "id");
		EnterpriseRepositoryGroup enterpriseRepositoryGroup = new EnterpriseRepositoryGroup();
		enterpriseRepositoryGroup.setId(id);
		enterpriseRepositoryGroup.setDelFlag(BaseBean.DEL_FLAG_DELETE);
		return enterpriseRepositoryGroupDao.updateByPrimaryKeySelective(enterpriseRepositoryGroup);
	}

}
