// Generated by XCloud DoPaaS for Codegen, refer: http://dts.devops.wl4g.com

/*
 * Copyright 2017 ~ 2025 the original author or authors. <wanglsir@gmail.com, 983708408@qq.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.wl4g.dopaas.udm.web;

import com.wl4g.component.common.web.rest.RespBase;
import com.wl4g.component.core.page.PageHolder;
import com.wl4g.component.core.web.BaseController;
import com.wl4g.component.rpc.feign.core.context.RpcContextHolder;
import com.wl4g.dopaas.common.bean.udm.EeDocumentRepoVersion;
import com.wl4g.dopaas.udm.service.EeDocumentRepoVersionService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import static org.springframework.web.bind.annotation.RequestMethod.*;

/**
* {@link EeDocumentRepoVersion}
*
* @author root
* @version 0.0.1-SNAPSHOT
* @Date 
* @since v1.0
*/
@RestController
@RequestMapping("/eedocumentrepoversion")
public class EeDocumentRepoVersionController extends BaseController {

    @Autowired
    private EeDocumentRepoVersionService eeDocumentRepoVersionService;

    @RequestMapping(value = "/list", method = { GET })
    public RespBase<PageHolder<EeDocumentRepoVersion>> list(PageHolder<EeDocumentRepoVersion> pm, EeDocumentRepoVersion eeDocumentRepoVersion) {
        RpcContextHolder.get().set("pm",pm);
        RespBase<PageHolder<EeDocumentRepoVersion>> resp = RespBase.create();
        resp.setData(eeDocumentRepoVersionService.page(eeDocumentRepoVersion));
        return resp;
    }

    @RequestMapping(value = "/save", method = { POST, PUT })
    public RespBase<?> save(@RequestBody EeDocumentRepoVersion eeDocumentRepoVersion) {
        RespBase<Object> resp = RespBase.create();
        eeDocumentRepoVersionService.save(eeDocumentRepoVersion);
        return resp;
    }

    @RequestMapping(value = "/detail", method = { GET })
    public RespBase<EeDocumentRepoVersion> detail(@RequestParam(required = true) Long id) {
        RespBase<EeDocumentRepoVersion> resp = RespBase.create();
        resp.setData(eeDocumentRepoVersionService.detail(id));
        return resp;
    }

    @RequestMapping(value = "/del", method = { POST, DELETE })
    public RespBase<?> del(@RequestParam(required = true) Long id) {
        RespBase<Object> resp = RespBase.create();
        eeDocumentRepoVersionService.del(id);
        return resp;
    }

}
