// Generated by XCloud DoPaaS for Codegen, refer: http://dts.devops.wl4g.com

/*
 * Copyright 2017 ~ 2025 the original author or authors. <wanglsir@gmail.com, 983708408@qq.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.wl4g.dopaas.udm.web;


import com.wl4g.component.common.web.rest.RespBase;
import com.wl4g.component.core.bean.model.PageHolder;
import com.wl4g.component.core.web.BaseController;
import com.wl4g.dopaas.common.bean.udm.EnterpriseApiModule;
import com.wl4g.dopaas.udm.service.EnterpriseApiModuleService;
import com.wl4g.dopaas.udm.service.dto.EnterpriseApiModulePageRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

import static org.springframework.web.bind.annotation.RequestMethod.*;

/**
* {@link EnterpriseApiModule}
*
* @author root
* @version 0.0.1-SNAPSHOT
* @Date 
* @since v1.0
*/
@RestController
@RequestMapping("/enterpriseapimodule")
public class EnterpriseApiModuleController extends BaseController {

    @Autowired
    private EnterpriseApiModuleService enterpriseApiModuleService;

    @RequestMapping(value = "/list", method = { GET })
    public RespBase<PageHolder<EnterpriseApiModule>> list(EnterpriseApiModulePageRequest enterpriseApiModulePageRequest,PageHolder<EnterpriseApiModule> pm) {
        RespBase<PageHolder<EnterpriseApiModule>> resp = RespBase.create();
        enterpriseApiModulePageRequest.setPm(pm);
        resp.setData(enterpriseApiModuleService.page(enterpriseApiModulePageRequest));
        return resp;
    }

    @RequestMapping(value = "/getByVersionIdAndParentId", method = { GET })
    public RespBase<List<EnterpriseApiModule>> getByVersionIdAndParentId(Long versionId, Long parentId) {
        RespBase<List<EnterpriseApiModule>> resp = RespBase.create();
        resp.setData(enterpriseApiModuleService.getByVersionIdAndParentId(versionId, parentId));
        return resp;
    }

    @RequestMapping(value = "/save", method = { POST, PUT })
    public RespBase<?> save(@RequestBody EnterpriseApiModule enterpriseApiModule) {
        RespBase<Object> resp = RespBase.create();
        enterpriseApiModuleService.save(enterpriseApiModule);
        return resp;
    }

    @RequestMapping(value = "/detail", method = { GET })
    public RespBase<EnterpriseApiModule> detail(@RequestParam(required = true) Long id) {
        RespBase<EnterpriseApiModule> resp = RespBase.create();
        resp.setData(enterpriseApiModuleService.detail(id));
        return resp;
    }

    @RequestMapping(value = "/del", method = { POST, DELETE })
    public RespBase<?> del(@RequestParam(required = true) Long id) {
        RespBase<Object> resp = RespBase.create();
        enterpriseApiModuleService.del(id);
        return resp;
    }

}
