# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Environment(Dev) configuration. ####
#
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource # com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver

redis:
  passwd: ${REDIS_PASSWD:123456}
  connect-timeout: 10000
  max-attempts: 10
  # Redis server nodes, support standalone mode single node and cluster mode multiple nodes, separated by commas.
  nodes: ${DOPAAS_REDIS_NODES:redis.dopaas.dev:6379,redis.dopaas.dev:6380,redis.dopaas.dev:6381,redis.dopaas.dev:7379,redis.dopaas.dev:7380,redis.dopaas.dev:7381}

# Example configuration.
example:
  firstName: 王
  lastName: jack
