# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Configuration of specical on which DoPaaS(uci-server) service(fat). ####
#
spring:
  infra:
    support:
        jedis:
          passwd: ${UCI_DOPAAS_REDIS_PASSWD:123456}
          connect-timeout: 10000
          max-attempts: 10
          # Redis server nodes, support standalone mode single node and cluster mode multiple nodes, separated by commas.
          nodes: ${UCI_DOPAAS_REDIS_NODES:redis.uci.dopaas.fat:6379,redis.uci.dopaas.fat:6380,redis.uci.dopaas.fat:6381,redis.uci.dopaas.fat:7379,redis.uci.dopaas.fat:7380,redis.uci.dopaas.fat:7381}
    iam:
      cors:
        rules:
          '[/**]':
            allows-origins:
              - https://${DOPAAS_ZONE:wl4g.fat}
              - http://${DOPAAS_ZONE:wl4g.fat}
              - https://*.${DOPAAS_ZONE:wl4g.fat}
              - http://*.${DOPAAS_ZONE:wl4g.fat}
      acl:
        secure: false # Turn off protection will trust any same intranet IP.
        allowIpRange: ${DOPAAS_IAM_ACL_ALLOW:127.0.0.1}
        denyIpRange: ${DOPAAS_IAM_ACL_DENY}
      client:
        server-uri: http://iam.${DOPAAS_ZONE:wl4g.fat}/iam-web
        unauthorized-uri: ${spring.iam.client.server-uri}/view/403.html
        success-uri: http://dopaas.${DOPAAS_ZONE:wl4g.fat}/#/ci/taskhis
    dopaas.uci:
      testing-report:
        upload-path: /mnt/dist1/upload
        download-url: http://uci.dopaas.fat/ci-server/fs/download