// Generated by XCloud PaaS for Codegen, refer: http://dts.devops.wl4g.com

/*
 * Copyright 2017 ~ 2025 the original author or authors. <wanglsir@gmail.com, 983708408@qq.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.wl4g.paas.udm.service.impl;

import static com.wl4g.component.common.lang.Assert2.notNullOf;
import static java.util.Objects.isNull;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.wl4g.component.core.bean.BaseBean;
import com.wl4g.component.core.bean.model.PageHolder;
import com.wl4g.component.rpc.feign.core.context.RpcContextHolder;
import com.wl4g.paas.common.bean.udm.EeDocumentRepoGroup;
import com.wl4g.paas.udm.data.EeDocumentRepoGroupDao;
import com.wl4g.paas.udm.service.EeDocumentRepoGroupService;

/**
 * service implements of {@link EeDocumentRepoGroup}
 *
 * @author root
 * @version 0.0.1-SNAPSHOT
 * @Date
 * @since v1.0
 */
@Service
public class EeDocumentRepoGroupServiceImpl implements EeDocumentRepoGroupService {

	@Autowired
	private EeDocumentRepoGroupDao eeDocumentRepoGroupDao;

	@Override
	public PageHolder<EeDocumentRepoGroup> page(EeDocumentRepoGroup eeDocumentRepoGroup) {
		PageHolder pm = RpcContextHolder.get().get("pm", PageHolder.class);
		pm.count().startPage();
		pm.setRecords(eeDocumentRepoGroupDao.list(eeDocumentRepoGroup));
		return pm;
	}

	@Override
	public int save(EeDocumentRepoGroup eeDocumentRepoGroup) {
		if (isNull(eeDocumentRepoGroup.getId())) {
			eeDocumentRepoGroup.preInsert();
			return eeDocumentRepoGroupDao.insertSelective(eeDocumentRepoGroup);
		} else {
			eeDocumentRepoGroup.preUpdate();
			return eeDocumentRepoGroupDao.updateByPrimaryKeySelective(eeDocumentRepoGroup);
		}
	}

	@Override
	public EeDocumentRepoGroup detail(Long id) {
		notNullOf(id, "id");
		return eeDocumentRepoGroupDao.selectByPrimaryKey(id);
	}

	@Override
	public int del(Long id) {
		notNullOf(id, "id");
		EeDocumentRepoGroup eeDocumentRepoGroup = new EeDocumentRepoGroup();
		eeDocumentRepoGroup.setId(id);
		eeDocumentRepoGroup.setDelFlag(BaseBean.DEL_FLAG_DELETE);
		return eeDocumentRepoGroupDao.updateByPrimaryKeySelective(eeDocumentRepoGroup);
	}

}
