<!-- ${watermark} -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>${organName?uncap_first}-${projectName?uncap_first}-starter</artifactId>
	<packaging>jar</packaging>
	<name>${organName?cap_first} ${projectName?cap_first} Starter</name>
	<url>http://${projectName?uncap_first}.${organName?uncap_first}.${organType}</url>
	<parent>
		<groupId>${organType?uncap_first}.${organName?uncap_first}</groupId>
		<artifactId>${organName?uncap_first}-${projectName?uncap_first}</artifactId>
		<version>${version?uncap_first}</version>
	</parent>
	<properties>
		<java.version>1.8</java.version>
		<final.name>${projectName?uncap_first}-server</final.name>
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.wl4g</groupId>
				<artifactId>xcloud-bom</artifactId>
				<version>master</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>${organType?uncap_first}.${organName?uncap_first}</groupId>
			<artifactId>${organName?uncap_first}-${projectName?uncap_first}-service</artifactId>
			<version>${version?uncap_first}</version>
		</dependency>
		<#if javaSpecs.isConf(extraOptions, "gen.iam.security-mode", "cluster")>
		<dependency>
			<groupId>com.wl4g</groupId>
			<artifactId>xcloud-iam-test</artifactId>
			<scope>test</scope>
		</dependency>
		</#if>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<build>
		<finalName>${projectName?uncap_first}-server</finalName>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
				<excludes>
					<exclude>script/**</exclude>
				</excludes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<includes>
					<include>**/*.*</include>
				</includes>
				<filtering>false</filtering>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					${r'<source>${java.version}</source>'}
					${r'<target>${java.version}</target>'}
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-sources</id>
						<phase>verify</phase>
						<goals>
							<goal>jar-no-fork</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		<#-- Build artifact package type.(MvnAssTar/SpringExecJar) -->
		<#if javaSpecs.isConf(extraOptions, "gen.build.assets-type", "MvnAssTar")>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					${r'<finalName>${final.name}-${project.version}-bin</finalName>'}
					<!-- not append assembly id in release file name -->
					<appendAssemblyId>false</appendAssemblyId>
					<descriptors>
						<descriptor>src/main/assemble/package.xml</descriptor>
					</descriptors>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		<#elseif javaSpecs.isConf(extraOptions, "gen.build.assets-type", "SpringExecJar")>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<mainClass>${organType?lower_case}.${organName?lower_case}.${projecName?cap_first}Server</mainClass>
				</configuration>
			</plugin>
		</#if>
		</plugins>
	</build>
</project>