# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Environment(Dev) configuration. ####
#
spring:
  xcloud:
    component:
      support:
        jedis:
          passwd: ${UMC_DOPAAS_REDIS_PASSWD:zzx!@#$%}
          connect-timeout: 10000
          max-attempts: 10
          # Redis server nodes, support standalone mode single node and cluster mode multiple nodes, separated by commas.
          nodes: ${UMC_DOPAAS_REDIS_NODES:owner-node1:6379,owner-node1:6380,owner-node1:6381,owner-node3:6379,owner-node3:6380,owner-node3:6381}
        notification:
          mail:
            host: smtp.163.com
            port: 465
            username: babaa1f4@163.com
            password: XBurnerAir00
            protocol: smtp
          sms:
            aliyun:
              accessKeyId: ${ALIYUN_KEY}
              accessKeySecret: ${ALIYUN_SECRET}
          vms:
            aliyun:
              accessKeyId: ${ALIYUN_KEY}
              accessKeySecret: ${ALIYUN_SECRET}
              calledShowNumber: 055162153866
    iam:
      cors:
        rules:
          '[/**]':
            allows-origins:
              #- http://${DOPAAS_SERVICE_ZONE:wl4g.debug}
              #- http://${DOPAAS_SERVICE_ZONE:wl4g.debug:${server.port}}
              #- http://*.${DOPAAS_SERVICE_ZONE:wl4g.debug}
              #- http://*.${DOPAAS_SERVICE_ZONE:wl4g.debug:${server.port}}
              #- http://localhost:8080
              #- http://localhost:18080
              #- http://127.0.0.1:8080
              #- http://127.0.0.1:18080
              - '*'
      acl:
        secure: false # Turn off protection will trust any same intranet IP.
        allowIpRange: ${DOPAAS_IAM_ACL_ALLOW:127.0.0.1}
        denyIpRange: ${DOPAAS_IAM_ACL_DENY}
      client:
        # 为方便同事调用，当域名以debug，local，dev后缀结尾，跟localhost一样处理，同时修改前端 global_variable.js #55 ， 同时修改数据库sys_cluster_config
        server-uri: http://wl4g.debug:18080/iam-web
        unauthorized-uri: ${spring.xcloud.iam.client.server-uri}/view/403.html
        success-uri: http://wl4g.debug:8080/#/umc/config

# Spring-security config.
spring.security.user:
  name: sba_user
  password: hnGsFm6k0klJP9j

opentsdb:
  url: http://10.0.0.57
  port: 4242