# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Configuration of general on which DoPaaS(standalone) service(pro). ####
#
spring:
  xcloud:
    component:
      support:
        jedis:
          passwd: ${STANDALONE_DOPAAS_REDIS_PASSWD:123456}
          connect-timeout: 10000
          max-attempts: 10
          # Redis server nodes, support standalone mode single node and cluster mode multiple nodes, separated by commas.
          nodes: ${STANDALONE_DOPAAS_REDIS_NODES:redis.standalone.wl4g.com:6379,redis.standalone.wl4g.com:6380,redis.standalone.wl4g.com:6381,redis.standalone.wl4g.com:7379,redis.standalone.wl4g.com:7380,redis.standalone.wl4g.com:7381}
    iam:
      cors:
        rules:
          '[/**]':
            allows-origins:
              - https://${DOPAAS_ZONE:wl4g.com}
              - http://${DOPAAS_ZONE:wl4g.com}
              - https://*.${DOPAAS_ZONE:wl4g.com}
              - http://*.${DOPAAS_ZONE:wl4g.com}
      acl:
        secure: false # Turn off protection will trust any same intranet IP.
        allowIpRange: ${DOPAAS_IAM_ACL_ALLOW:127.0.0.1}
        denyIpRange: ${DOPAAS_IAM_ACL_DENY}
      client:
        server-uri: ${DOPAAS_SCHEMA:https}://iam.${DOPAAS_ZONE:wl4g.com}/iam-web
        unauthorized-uri: ${spring.xcloud.iam.client.server-uri}/view/403.html
        success-uri: ${DOPAAS_SCHEMA:https}://dopaas.${DOPAAS_ZONE:wl4g.com}/#/ci/taskhis
  datasource:
    type: com.zaxxer.hikari.HikariDataSource # com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
#    druid:
#      url: ${STANDALONE_DOPAAS_DB_URL:jdbc:mysql://rds.standalone.wl4g.com:3306/dopaas?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&autoReconnect=true}
#      username: ${STANDALONE_DOPAAS_DB_USER:dopaas}
      # Ciphertext db password, e.g @see:com.wl4g.component.data.config.DruidAutoConfiguration#druidDataSource()
#      password: ${STANDALONE_DOPAAS_DB_PASSWD:DFDDD7F502E694F3E40D750FEEAE423D}
#      initial-size: 10
#      max-active: 100
#      min-idle: 10
#      max-wait: 60000
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      filters: stat,wall
#      log-slow-sql: true
