# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### Environment(FAT Test) configuration. ####
#
spring:
  cloud:
    devops:
      iam:
        cors:
          rules:
            /**:
              allowsOrigins:
                - https://${DEVOPS_DOMAIN_TOP:wl4g.fat}
                - http://${DEVOPS_DOMAIN_TOP:wl4g.fat}
                - https://*.${DEVOPS_DOMAIN_TOP:wl4g.fat}
                - http://*.${DEVOPS_DOMAIN_TOP:wl4g.fat}
        acl:
          secure: false # Turn off protection will trust any same intranet IP.
          allowIpRange: ${DEVOPS_IAM_ACL_ALLOW:127.0.0.1}
          denyIpRange: ${DEVOPS_IAM_ACL_DENY}
        client:
          server-uri: http://iam.${DEVOPS_DOMAIN_TOP:wl4g.fat}/iam-server
          unauthorized-uri: ${spring.cloud.devops.iam.client.server-uri}/view/403.html
          success-uri: http://devops.${DEVOPS_DOMAIN_TOP:wl4g.fat}/#/ci/taskhis
      ci:
        pipeline: # Pipeline configuration.
          #workspace: # Default by to {user.home}/.ci-workspace
          executor:
            concurrency: 10
            accept-queue: 2
          vcs:
            gitlab:
              search-projects-default-page-limit: 20
          build:
            job-max-clean-interval-ms: 30_000
            job-timeout-ms: 3000_000
            shared-dependency-try-timeout-ms: 1200_000
          deploy:
            #remoteHome-tmp-dir: # Default by to $HOME/.ci-temporary
            cipher-key: 03DE18C2FC4E605F
            transfer-timeout-ms: 300_000
            docker-native:
              docker-push-username: xburnerair00
              docker-push-password: hwj13535248668
          tested-report:
            upload-path: /mnt/dist1/upload
            download-url: http://ci.anjiancloud.alpha/ci-server/fs/download
      support:
        notification:
          mail:
            host: smtp.163.com
            port: 465
            username: babaa1f4@163.com
            password: XBurnerAir00
            protocol: smtp
          sms:
            aliyun:
              accessKeyId: ${ALIYUN_KEY}
              accessKeySecret: ${ALIYUN_SECRET}
          vms:
            aliyun:
              accessKeyId: ${ALIYUN_KEY}
              accessKeySecret: ${ALIYUN_SECRET}
              calledShowNumber: 055162153866

  # Datasource configuration.
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://${DEVOPS_DB_URL:owner-node1:3306}/${DEVOPS_DB_NAME:devops}?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: ${DEVOPS_DB_USER:gzsm}
      password: ${DEVOPS_DB_PASSWD:gzsm@%#jh?}
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall
      log-slow-sql: true

# Redis configuration.
redis:
  passwd: ${REDIS_PASSWD:zzx!@#$%}
  connect-timeout: 10000
  max-attempts: 10
  # Redis's cluster nodes.
  nodes: ${REDIS_NODES:owner-node1:6379,owner-node1:6380,owner-node1:6381,owner-node3:6379,owner-node3:6380,owner-node3:6381}
